#!/usr/bin/env python3
# SPDX-FileCopyrightText: Christian Amsüss and the aiocoap contributors
#
# SPDX-License-Identifier: MIT

"""This script can be used to access the aiocoap command line client when its
entry points have not been installed (eg. when running from the source
directory)."""

import asyncio
import aiocoap.cli.client

asyncio.run(aiocoap.cli.client.main())
