#!/usr/bin/env python3
# SPDX-FileCopyrightText: Christian Amsüss and the aiocoap contributors
#
# SPDX-License-Identifier: MIT

"""This script can be used to access the aiocoap command line resource
directory when its entry points have not been installed (eg. when running from
the source directory)."""

import aiocoap.cli.rd

# When changing this, beware that the projects.scripts entry points need to be
# changed as well.
aiocoap.cli.rd.sync_main()
