#!/usr/bin/env python3
# Copyright (c) 2012-2014 Maciej Wasilak <http://sixpinetrees.blogspot.com/>,
# Copyright (c) 2013-2014 Christian Amsüss <c.amsuess@energyharvesting.at>
#
# SPDX-License-Identifier: MIT

"""This script can be used to access the aiocoap file server
when setup.py is not used to create an entry point for it (eg. when
running from the source directory)."""

import aiocoap.cli.fileserver

aiocoap.cli.fileserver.FileServerProgram.sync_main()
