#!/usr/bin/env python3

"""This script can be used to access the aiocoap command line proxy when
setup.py is not used to create an entry point for it (eg. when running from the
source directory)."""

import aiocoap.cli.proxy

aiocoap.cli.proxy.sync_main()
