#!/usr/bin/env python3

"""This script can be used to access the aiocoap command line resource
directory when setup.py is not used to create an entry point for it (eg. when
running from the source directory)."""

import aiocoap.cli.rd

aiocoap.cli.rd.sync_main()
